FROM ubuntu:xenial
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    curl \
 && rm -rf /var/lib/apt/lists/*

ADD scripts/register.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/register.sh"]
